source/accounts/urls.py
from django.urls import path

from django.contrib.auth.views import LoginView, LogoutView

from accounts.views import register_view, UserDetailView, UserChangeView, UserChangePasswordView

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create/', register_view, name='register'),
    path('user/<int:pk>/detail/', UserDetailView.as_view(), name='user_detail'),
    path('user/<int:pk>/update/', UserChangeView.as_view(), name='user_update'),
    path('user/<int:pk>/change-password/', UserChangePasswordView.as_view(), name='user_change_password')

]

app_name = 'accounts'

source/main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path

from webapp.views import ProductCreateView, ProductUpdateView, ProductDeleteView, ProductDetailView, ReviewCreateView, \
    ReviewUpdateView, ReviewDeleteView
from .views import ProductListView

urlpatterns = [
    path('', ProductListView.as_view(), name='index'),
    path('products/create/', ProductCreateView.as_view(), name='create_product'),
    path('products/<int:pk>/update/', ProductUpdateView.as_view(), name='update_product'),
    path('products/<int:pk>/delete/', ProductDeleteView.as_view(), name='delete_product'),
    path('products/<int:pk>/', ProductDetailView.as_view(), name='detail_product'),
    path('reviews/<int:product_pk>/create/', ReviewCreateView.as_view(), name='create_review'),
    path('reviews/<int:pk>/update/', ReviewUpdateView.as_view(), name='update_review'),
    path('reviews/<int:pk>/delete/', ReviewDeleteView.as_view(), name='delete_review')
]

app_name = 'webapp'

source/accounts/models.py
from django.contrib.auth.models import User
from django.db import models


class Profile(models.Model):
    user = models.OneToOneField(User, related_name='profile', on_delete=models.CASCADE, verbose_name='Пользователь')
    avatar = models.ImageField(null=True, blank=True, upload_to='user_pics', verbose_name='Аватар')

    def __str__(self):
        return self.user.get_full_name() + "'s Profile"

    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'

source/webapp/models.py
from django.db import models
from django.contrib.auth.models import User
CATEGORY_CHOICES = [
    ('other', 'Другое'),
    ('kitchen', 'Кухня'),
    ('electronics', 'Электроника'),
    ('children', 'Дети')
]


class Product(models.Model):
    name = models.CharField(max_length=128, verbose_name='Название')
    category = models.CharField(verbose_name='Категория', max_length=64, choices=CATEGORY_CHOICES,
                                default=CATEGORY_CHOICES[0][0])
    description = models.TextField(null=True, blank=True, verbose_name='Описание', max_length=512)
    img = models.ImageField(verbose_name='Картинка', null=True, blank=True, upload_to='product_pics')

    def __str__(self):
        return self.name

    def get_average(self):
        reviews = self.reviews.all()
        if reviews:
            total = sum([review.mark for review in reviews])
            return round(total/len(reviews), 2)
        return 0

    def get_star(self):
        average = self.get_average()
        number = []
        for i in range(1, 6):
            if average > 0.00:
                if average - 1 < 0.00:
                    number.append(str(average * 100))
                    average -= 1
                else:
                    average -= 1
                    number.append(str(100))
            else:
                number.append(str(0))
        return number



class Review(models.Model):
    author = models.ForeignKey(User, on_delete=models.PROTECT, related_name='reviews')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='reviews')
    text = models.TextField(verbose_name='Текст отзыва', max_length=512)
    mark = models.DecimalField(verbose_name='Оценка', max_digits=3, decimal_places=2)

    def __str__(self):
        return "Оценка {} к продукту {}".format(self.author, self.product)


    def get_star(self):
        mark = self.mark
        number = []
        for i in range(1, 6):
            if mark > 0.00:
                if mark - 1 < 0.00:
                    number.append(str(mark * 100))
                    mark -= 1
                else:
                    mark -= 1
                    number.append(str(100))
            else:
                number.append(str(0))
        return number

source/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

from accounts.models import Profile


class SignUpForm(forms.ModelForm):
    password = forms.CharField(label="Пароль", strip=False, widget=forms.PasswordInput)
    password_confirm = forms.CharField(label="Подтвердите пароль", widget=forms.PasswordInput, strip=False)
    email = forms.CharField(label='Email', required=True)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

    def clean_username(self):
        username = self.cleaned_data['username']
        try:
            User.objects.get(username=username)
            raise ValidationError("Такой пользователь уже есть", code='username_taken')
        except User.DoesNotExist:
            return username

    def clean_email(self):
        email = self.cleaned_data['email']
        try:
            User.objects.get(email=email)
            raise ValidationError("Эта почта уже используется", code='email_taken')
        except User.DoesNotExist:
            return email

    def clean(self):
        super().clean()
        password = self.cleaned_data.get("password")
        password_confirm = self.cleaned_data.get("password_confirm")
        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError('Пароли не совпадают!')

    class Meta:
        model = User
        fields = ['username', 'password', 'password_confirm', 'first_name', 'last_name', 'email']
        labels = {'username': 'Логин', 'first_name': 'Имя', 'last_name': 'Фамилия'}


class UserChangeForm(forms.ModelForm):
    avatar = forms.ImageField(label='Аватар', required=False)

    def get_initial_for_field(self, field, field_name):
        if field_name in self.Meta.profile_fields:
            return getattr(self.instance.profile, field_name)
        return super().get_initial_for_field(field,field_name)

    class Meta:
        model = User
        fields = ['first_name',  'email', 'avatar']
        labels = {'first_name': 'Имя', 'last_name': 'Фамилия', 'email': 'Email'}
        profile_fields = ['avatar']

    def save(self, commit=True):
        user = super().save(commit)
        self.save_profile(user)
        return user

    def save_profile(self, user, commit=True):
        profile = Profile.objects.get_or_create(user=user)[0]
        for field in self.Meta.profile_fields:
            setattr(profile, field, self.cleaned_data.get(field))
        if commit:
            profile.save()


class UserChangePasswordForm(forms.ModelForm):
    password = forms.CharField(max_length=100, required=True, label='Новый пароль',
                               widget=forms.PasswordInput)
    password_confirm = forms.CharField(max_length=100, required=True, label='Подтвердите новый пароль',
                                       widget=forms.PasswordInput)
    old_password = forms.CharField(max_length=100, required=True, label='Старый пароль',
                                   widget=forms.PasswordInput)

    def clean_old_password(self):
        old_password = self.cleaned_data.get('old_password')
        user = self.instance
        if not user.check_password(old_password):
            raise ValidationError('Invalid password.', code='invalid_password')
        return old_password

    def clean(self):
        super().clean()
        password_1 = self.cleaned_data.get('password')
        password_2 = self.cleaned_data.get('password_confirm')
        if password_1 != password_2:
            raise ValidationError('Passwords do not match.', code='passwords_do_not_match')
        return self.cleaned_data

    def save(self, commit=True):
        user = self.instance
        user.set_password(self.cleaned_data.get('password'))
        if commit:
            user.save()
        return user

    class Meta:
        model = User
        fields = ['password', 'password_confirm', 'old_password']

source/accounts/views.py
from django.contrib.auth import login
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import UpdateView, DetailView

from accounts.forms import SignUpForm, UserChangeForm, UserChangePasswordForm
from accounts.models import Profile


def register_view(request, *args, **kwargs):
    if request.method == 'POST':
        form = SignUpForm(data=request.POST)
        if form.is_valid():
            user = form.save()
            Profile.objects.create(user=user)
            login(request, user)
            return redirect('webapp:index')
    else:
        form = SignUpForm()
    return render(request, 'register.html', context={'form': form})


class UserDetailView(DetailView):
    model = User
    template_name = 'user_detail.html'
    context_object_name = 'user_obj'


class UserChangeView(UserPassesTestMixin, UpdateView):
    model = User
    template_name = 'user_update.html'
    context_object_name = 'user_obj'
    form_class = UserChangeForm

    def test_func(self):
        return self.get_object() == self.request.user

    def get_success_url(self):
        return reverse('accounts:user_detail', kwargs={'pk': self.object.pk})


class UserChangePasswordView(UserPassesTestMixin, UpdateView):
    model = User
    template_name = 'user_change_password.html'
    form_class = UserChangePasswordForm
    context_object_name = 'user_obj'

    def test_func(self):
        return self.get_object() == self.request.user

    def get_success_url(self):
        return reverse('accounts:login')

source/accounts/templates/register.html
{%  extends 'base.html' %}
{% block content %}
    <form action="{% url 'accounts:register' %} " method="post">
    {% include 'partial/form.html' %}
     <input type="submit" value="Зарегистрироваться" class="btn btn-primary">
    </form>
{% endblock %}

source/accounts/templates/user_change_password.html
{% extends 'base.html' %}
{% block title %}{{ user_obj.username }}{% endblock %}
{% block menu %}
    {% if user_obj == request.user %}
        <li class="nav-item"><a class="nav-link" href="{% url 'accounts:user_detail' user_obj.pk %}">Назад</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'accounts:user_update' user_obj.pk %}">Обновить профиль</a></li>
    {% endif %}
{% endblock %}
{% block content %}
    <h1>Поменять пароль: {{ user_obj.username }}</h1>
    <form action="{% url 'accounts:user_change_password' user_obj.pk %}" method="post">
        {% include 'partial/form.html' %}
    <input type="submit" value="Изменить" class="btn btn-primary">
    </form>
{% endblock %}

source/accounts/templates/user_detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}{{ user_obj.username }}{% endblock %}
{% block menu %}
    {% if user_obj == request.user %}
        <li class="nav-item"><a class="nav-link" href="{% url "accounts:user_update" user_obj.pk %}">Обновить профиль</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'accounts:user_change_password' user_obj.pk %}">Поменять пароль</a></li>
    {% endif %}
{% endblock %}
{% block content %}
    <div class="object row px-0">
    <div class="col-4">
        {% if user_obj.profile.avatar %}
        <img class="avatar" src="{{ user_obj.profile.avatar.url }}" width="210" height="210" alt="user picture">
            {% else %}
            <img class="avatar" src="{% static 'img/anonim.jpg' %}" width="210" height="210" alt="user picture">
        {% endif %}
    </div>
    <div class="col-8 pr-0 ">
     <h2 class="mx-auto mb-5">Профиль: {{ user_obj.username }}</h2>
    <div class="row">
        <div class="col-6 pl-5">
            <p class="d-block">Имя:</p>
        </div>
        <div class="col-6">
            <p><b>{{ user_obj.first_name }}</b></p>
        </div>
    </div>
     <div class="row ">
        <p class="col-6 pl-5">Email:</p>
        <p class="col-6"><b>{{ user_obj.email }}</b></p>
        </div>

    </div>
    </div>
        <div>
            <h2>Отзывы этого автора</h2>

    {% for review in user_obj.reviews.all %}
            <div class="review">
        <h3>Отзыв к <a href="{% url 'webapp:detail_product' review.product.id %}">{{ review.product }}</a></h3>
<p>{{ review.text }}</p>
<p>Оценка: <b>{{ review.mark }}</b></p>
            {% include 'review/star.html' %}
                {% if user_obj == request.user or perms.webapp.change_review %}
    <a href="{% url 'webapp:update_review' review.pk %}">Изменить отзыв</a>
    <a href="{% url 'webapp:delete_review' review.pk %}">Удалить отзыв</a>
            {% endif %}
            </div>
                {% endfor %}
    </div>


{% endblock %}

source/accounts/templates/user_update.html
{% extends 'base.html' %}
{% block title %}{{ user_obj.username }}{% endblock %}
{% block menu %}
    {% if user_obj == request.user %}
        <li class="nav-item"><a class="nav-link" href="{% url 'accounts:user_detail' user_obj.pk %}">Назад</a></li>
    {% endif %}
{% endblock %}
{% block content %}
    <h1>Обновить профиль: {{ user_obj.username }}</h1>
    <form action="{% url 'accounts:user_update' user_obj.pk %}" method="post" enctype="multipart/form-data">
        {% include 'partial/form.html' %}
    <input type="submit" value="Изменить" class="btn btn-primary">
    </form>
{% endblock %}