source/accounts/urls.py
from django.urls import path

from django.contrib.auth.views import LoginView, LogoutView

from accounts.views import register_view, UserDetailView, UserChangeView, UserChangePasswordView

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create/', register_view, name='register'),
    path('user/<int:pk>/detail/', UserDetailView.as_view(), name='user_detail'),
    path('user/<int:pk>/update/', UserChangeView.as_view(), name='user_update'),
    path('user/<int:pk>/change-password/', UserChangePasswordView.as_view(), name='user_change_password')

]

app_name = 'accounts'

source/main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path

from webapp.views import ProductCreateView, ProductUpdateView, ProductDeleteView, ProductDetailView, ReviewCreateView, \
    ReviewUpdateView, ReviewDeleteView
from .views import ProductListView

urlpatterns = [
    path('', ProductListView.as_view(), name='index'),
    path('products/create/', ProductCreateView.as_view(), name='create_product'),
    path('products/<int:pk>/update/', ProductUpdateView.as_view(), name='update_product'),
    path('products/<int:pk>/delete/', ProductDeleteView.as_view(), name='delete_product'),
    path('products/<int:pk>/', ProductDetailView.as_view(), name='detail_product'),
    path('reviews/<int:product_pk>/create/', ReviewCreateView.as_view(), name='create_review'),
    path('reviews/<int:pk>/update/', ReviewUpdateView.as_view(), name='update_review'),
    path('reviews/<int:pk>/delete/', ReviewDeleteView.as_view(), name='delete_review')
]

app_name = 'webapp'

source/webapp/models.py
from django.db import models
from django.contrib.auth.models import User
CATEGORY_CHOICES = [
    ('other', 'Другое'),
    ('kitchen', 'Кухня'),
    ('electronics', 'Электроника'),
    ('children', 'Дети')
]


class Product(models.Model):
    name = models.CharField(max_length=128, verbose_name='Название')
    category = models.CharField(verbose_name='Категория', max_length=64, choices=CATEGORY_CHOICES,
                                default=CATEGORY_CHOICES[0][0])
    description = models.TextField(null=True, blank=True, verbose_name='Описание', max_length=512)
    img = models.ImageField(verbose_name='Картинка', null=True, blank=True, upload_to='product_pics')

    def __str__(self):
        return self.name

    def get_average(self):
        reviews = self.reviews.all()
        if reviews:
            total = sum([review.mark for review in reviews])
            return round(total/len(reviews), 2)
        return 0

    def get_star(self):
        average = self.get_average()
        number = []
        for i in range(1, 6):
            if average > 0.00:
                if average - 1 < 0.00:
                    number.append(str(average * 100))
                    average -= 1
                else:
                    average -= 1
                    number.append(str(100))
            else:
                number.append(str(0))
        return number



class Review(models.Model):
    author = models.ForeignKey(User, on_delete=models.PROTECT, related_name='reviews')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='reviews')
    text = models.TextField(verbose_name='Текст отзыва', max_length=512)
    mark = models.DecimalField(verbose_name='Оценка', max_digits=3, decimal_places=2)

    def __str__(self):
        return "Оценка {} к продукту {}".format(self.author, self.product)


    def get_star(self):
        mark = self.mark
        number = []
        for i in range(1, 6):
            if mark > 0.00:
                if mark - 1 < 0.00:
                    number.append(str(mark * 100))
                    mark -= 1
                else:
                    mark -= 1
                    number.append(str(100))
            else:
                number.append(str(0))
        return number

source/webapp/forms.py
from django import forms
from django.core.exceptions import ValidationError

from webapp.models import Product, Review


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        exclude = []


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        exclude = ['product', 'author']

    def clean_mark(self):
        mark = self.cleaned_data['mark']
        if not 5.00 >= mark >= 1.00:
            raise(ValidationError("Оценка может принимать значение от 1.00 до 5.00"))
        return mark

source/webapp/views/product_views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView

from webapp.forms import ProductForm
from webapp.models import Product
from django.template.defaulttags import register
@register.filter
def get_item(dictionary, key):
    return dictionary.get(key)


class ProductListView(ListView):
    model = Product
    context_object_name = 'products'
    template_name = 'product/index.html'


class ProductDetailView(DetailView):
    model = Product
    context_object_name = 'product'
    template_name = 'product/detail.html'


class ProductCreateView(PermissionRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    template_name = 'product/create.html'
    permission_required = 'webapp.add_product'
    permission_denied_message = 'Доступ запрещен'

    def get_success_url(self):
        return reverse('webapp:detail_product', kwargs={'pk': self.object.pk})


class ProductUpdateView(PermissionRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    template_name = 'product/update.html'
    permission_required = 'webapp.change_product'
    permission_denied_message = 'Доступ запрещен'

    def get_success_url(self):
        return reverse('webapp:detail_product', kwargs={'pk': self.object.pk})


class ProductDeleteView(PermissionRequiredMixin,DeleteView):
    model = Product
    template_name = 'product/delete.html'
    success_url = reverse_lazy('webapp:index')
    permission_required = 'webapp.delete_product'
    permission_denied_message = 'Доступ запрещен'

source/webapp/views/review_views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView

from webapp.forms import ReviewForm
from webapp.models import Review, Product


class ReviewCreateView(LoginRequiredMixin, CreateView):
    form_class = ReviewForm
    model = Review
    template_name = 'review/create.html'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.product = self.get_product()
        return super().form_valid(form)

    def get_product(self):
        return Product.objects.get(id=self.kwargs['product_pk'])

    def get_success_url(self):
        return reverse('webapp:detail_product', kwargs={'pk':self.kwargs['product_pk']})


class ReviewUpdateView(PermissionRequiredMixin, UpdateView):
    model = Review
    form_class = ReviewForm
    template_name = 'review/update.html'
    success_url = reverse_lazy('webapp:index')
    permission_required = 'webapp.change_review'
    permission_denied_message = 'Доступ запрещен'

    def has_permission(self):
        return super().has_permission() or self.is_author(self.request.user)

    def is_author(self, user):
        return self.get_object().author == user


class ReviewDeleteView(PermissionRequiredMixin, DeleteView):
    model = Review
    template_name = 'review/delete.html'
    success_url = reverse_lazy('webapp:index')
    permission_required = 'webapp.delete_review'
    permission_denied_message = 'Доступ запрещен'

    def has_permission(self):
        return super().has_permission() or self.is_author(self.request.user)

    def is_author(self, user):
        return self.get_object().author == user

source/webapp/templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block styles %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item"><a href="{% url 'webapp:index' %}" class="nav-link">На главную</a></li>
            {% block menu %}{% endblock %}
        </ul>
    <ul class="navbar-nav ml-auto">
            {% if request.user.is_authenticated %}
                <li class="nav-item"><a href="{% url 'accounts:user_detail' request.user.pk %}" class="nav-link">
                    Привет, {{ request.user.username }}!
                </a></li>
                <li class="nav-item"><a href="{% url 'accounts:logout' %}" class="nav-link">Выход</a></li>
            {% else %}
                <li class="nav-item"><a href="{% url 'accounts:register' %}" class="nav-link">Регистрация</a></li>
                <li class="nav-item"><a href="{% url 'accounts:login' %}" class="nav-link">Вход</a></li>
            {% endif %}
        </ul>
    </div>
</nav>
<div class="container mt-3 mb-3">
    {% block content %}{% endblock %}
</div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="{% static 'js/main.js' %}"></script>
{% block scripts %}{% endblock %}
</body>
</html>