source/main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path

from webapp.views import ProductCreateView, ProductUpdateView, ProductDeleteView, ProductDetailView, ReviewCreateView, \
    ReviewUpdateView, ReviewDeleteView
from .views import ProductListView

urlpatterns = [
    path('', ProductListView.as_view(), name='index'),
    path('products/create/', ProductCreateView.as_view(), name='create_product'),
    path('products/<int:pk>/update/', ProductUpdateView.as_view(), name='update_product'),
    path('products/<int:pk>/delete/', ProductDeleteView.as_view(), name='delete_product'),
    path('products/<int:pk>/', ProductDetailView.as_view(), name='detail_product'),
    path('reviews/<int:product_pk>/create/', ReviewCreateView.as_view(), name='create_review'),
    path('reviews/<int:pk>/update/', ReviewUpdateView.as_view(), name='update_review'),
    path('reviews/<int:pk>/delete/', ReviewDeleteView.as_view(), name='delete_review')
]

app_name = 'webapp'

source/webapp/models.py
from django.db import models
from django.contrib.auth.models import User
CATEGORY_CHOICES = [
    ('other', 'Другое'),
    ('kitchen', 'Кухня'),
    ('electronics', 'Электроника'),
    ('children', 'Дети')
]


class Product(models.Model):
    name = models.CharField(max_length=128, verbose_name='Название')
    category = models.CharField(verbose_name='Категория', max_length=64, choices=CATEGORY_CHOICES,
                                default=CATEGORY_CHOICES[0][0])
    description = models.TextField(null=True, blank=True, verbose_name='Описание', max_length=512)
    img = models.ImageField(verbose_name='Картинка', null=True, blank=True, upload_to='product_pics')

    def __str__(self):
        return self.name

    def get_average(self):
        reviews = self.reviews.all()
        if reviews:
            total = sum([review.mark for review in reviews])
            return round(total/len(reviews), 2)
        return 0

    def get_star(self):
        average = self.get_average()
        number = []
        for i in range(1, 6):
            if average > 0.00:
                if average - 1 < 0.00:
                    number.append(str(average * 100))
                    average -= 1
                else:
                    average -= 1
                    number.append(str(100))
            else:
                number.append(str(0))
        return number



class Review(models.Model):
    author = models.ForeignKey(User, on_delete=models.PROTECT, related_name='reviews')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='reviews')
    text = models.TextField(verbose_name='Текст отзыва', max_length=512)
    mark = models.DecimalField(verbose_name='Оценка', max_digits=3, decimal_places=2)

    def __str__(self):
        return "Оценка {} к продукту {}".format(self.author, self.product)


    def get_star(self):
        mark = self.mark
        number = []
        for i in range(1, 6):
            if mark > 0.00:
                if mark - 1 < 0.00:
                    number.append(str(mark * 100))
                    mark -= 1
                else:
                    mark -= 1
                    number.append(str(100))
            else:
                number.append(str(0))
        return number

source/webapp/forms.py
from django import forms
from django.core.exceptions import ValidationError

from webapp.models import Product, Review


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        exclude = []


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        exclude = ['product', 'author']

    def clean_mark(self):
        mark = self.cleaned_data['mark']
        if not 5.00 >= mark >= 1.00:
            raise(ValidationError("Оценка может принимать значение от 1.00 до 5.00"))
        return mark

source/webapp/views/product_views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView

from webapp.forms import ProductForm
from webapp.models import Product
from django.template.defaulttags import register
@register.filter
def get_item(dictionary, key):
    return dictionary.get(key)


class ProductListView(ListView):
    model = Product
    context_object_name = 'products'
    template_name = 'product/index.html'


class ProductDetailView(DetailView):
    model = Product
    context_object_name = 'product'
    template_name = 'product/detail.html'


class ProductCreateView(PermissionRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    template_name = 'product/create.html'
    permission_required = 'webapp.add_product'
    permission_denied_message = 'Доступ запрещен'

    def get_success_url(self):
        return reverse('webapp:detail_product', kwargs={'pk': self.object.pk})


class ProductUpdateView(PermissionRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    template_name = 'product/update.html'
    permission_required = 'webapp.change_product'
    permission_denied_message = 'Доступ запрещен'

    def get_success_url(self):
        return reverse('webapp:detail_product', kwargs={'pk': self.object.pk})


class ProductDeleteView(PermissionRequiredMixin,DeleteView):
    model = Product
    template_name = 'product/delete.html'
    success_url = reverse_lazy('webapp:index')
    permission_required = 'webapp.delete_product'
    permission_denied_message = 'Доступ запрещен'

source/webapp/views/review_views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView

from webapp.forms import ReviewForm
from webapp.models import Review, Product


class ReviewCreateView(LoginRequiredMixin, CreateView):
    form_class = ReviewForm
    model = Review
    template_name = 'review/create.html'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.product = self.get_product()
        return super().form_valid(form)

    def get_product(self):
        return Product.objects.get(id=self.kwargs['product_pk'])

    def get_success_url(self):
        return reverse('webapp:detail_product', kwargs={'pk':self.kwargs['product_pk']})


class ReviewUpdateView(PermissionRequiredMixin, UpdateView):
    model = Review
    form_class = ReviewForm
    template_name = 'review/update.html'
    success_url = reverse_lazy('webapp:index')
    permission_required = 'webapp.change_review'
    permission_denied_message = 'Доступ запрещен'

    def has_permission(self):
        return super().has_permission() or self.is_author(self.request.user)

    def is_author(self, user):
        return self.get_object().author == user


class ReviewDeleteView(PermissionRequiredMixin, DeleteView):
    model = Review
    template_name = 'review/delete.html'
    success_url = reverse_lazy('webapp:index')
    permission_required = 'webapp.delete_review'
    permission_denied_message = 'Доступ запрещен'

    def has_permission(self):
        return super().has_permission() or self.is_author(self.request.user)

    def is_author(self, user):
        return self.get_object().author == user

source/webapp/templates/product/create.html
{% extends 'base.html' %}
{% block title %}Добавить товар{% endblock %}
{% block content %}
    <h1 class="text-center">Создать товар</h1>
    <form action="{% url "webapp:create_product" %}" method="POST" enctype="multipart/form-data">
        {% include 'partial/form.html' %}
        <input type="submit" value="Создать" class="btn btn-primary">
    </form>
{% endblock %}

source/webapp/templates/product/delete.html
{% extends "base.html" %}
{% block title %}Удалить товар{% endblock %}
{% block content %}
    <h3>Вы уверены что хотите  удалить товар :<br>"{{ object }}"?</h3>
    <form method="POST"  class="text-center">
        {% csrf_token %}
        <div class="confirm d-flex justify-content-center">
            <p><input type="submit" value="Да" class="mt-5 btn btn-danger"></p>
            <p><a href="{% url 'webapp:index' %}" class="mt-5 btn  btn-primary">Нет</a></p>
        </div>
    </form>
{% endblock %}

source/webapp/templates/product/detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block menu %}
    {% if perms.webapp.change_product %}
     <li class="nav-item"><a href="{% url 'webapp:update_product' product.pk %}" class="nav-link">Изменить товар</a></li>
     <li class="nav-item"><a href="{% url 'webapp:delete_product' product.pk %}" class="nav-link">Удалить товар</a></li>
    {% endif %}
    {% if request.user.is_authenticated %}
    <li class="nav-item"><a href="{% url 'webapp:create_review' product.pk %}" class="nav-link">Добавить отзыв к товару</a></li>
    {% endif %}
{% endblock %}
{% block content %}
<div class="row ">
        <div class="col-6">
                    {% if product.img %}
                    <img src="{{ product.img.url }}" class="product-image"  alt="{{ product.name }}">
                    {% else %}
                    <img src="{% static 'img/no-photo.png' %}"   class= "product-image" alt="{{ product.name }}">
                    {% endif %}
        </div>
                    <div class="card-body col-6">
                        <h3 class="card-title">{{ product.name }}</h3>
                        <h6>Рейтинг товара по отзывам: {{ product.get_average }}</h6>
                        {% include 'product/star.html' %}
                        <p class="card-text">Категория: {{ product.get_category_display }}</p>
                        <p>Описание: <br>
                            {% if product.description %}
                                {{ product.description }}
                            {% else %}
                                У этого товара нет описания...
                            {% endif %}
                        </p>

                    </div>
                </div>
    {% for review in product.reviews.all %}
    {% include 'review/review_list.html' %}
    {% endfor %}
{% endblock %}

source/webapp/templates/product/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}Товары{% endblock %}
{% block menu %}
    {% if perms.webapp.add_product %}
        <li class="nav-item"><a href="{% url 'webapp:create_product' %}" class="nav-link">Добавить товар</a></li>
    {% endif %}
{% endblock %}
{% block content %}
    <h1 class="text-center">Товары</h1>
    <div class="row">
        {% for product in products %}
            <div class="col col-4">
                <div class="card">
                    {% if product.img %}
                    <img src="{{ product.img.url }}"   class="card-img-top" alt="{{ product.name }}">
                    {% else %}
                    <img src="{% static 'img/no-photo.png' %}"  class="card-img-top" alt="{{ product.name }}">
                    {% endif %}
                    <div class="card-body">
                        <h5 class="card-title">{{ product.name }}
                            {% if perms.webapp.add_product %}
                            <a href="{% url 'webapp:update_product' product.pk %}"><i class="far fa-edit"></i></a>
                            <a href="{% url 'webapp:delete_product' product.pk %}"><i class="far fa-trash-alt"></i></a>
                            {% endif %}
                        </h5>
                        <h3>Рейтинг: {{ product.get_average }}</h3>
                        {% include 'product/star.html' %}
                        <p class="card-text">{{ product.get_category_display }}</p>
                        <div class="text-center my-2">
                        <a href="{% url 'webapp:detail_product' product.pk %}"
                           class="btn btn-primary text-center">Подробнее</a>
                        </div>
                        {% if user.is_authenticated %}
                            <div class="text-center my-2">
                        <a href="{% url 'webapp:create_review' product.pk %}" class="btn btn-default">Оставить отзыв</a>
                            </div>
                        {% endif %}

                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

source/webapp/templates/product/star.html
<div class="col-12">
    <div class="star">
        <span class="star star-under fa fa-star"></span>
        <span class="star star-over fa fa-star "
        style="width:{{ product.get_star.0 }}%"></span>
    </div>
    <div class="star">
                <span class="star star-under fa fa-star"></span>
                <span class="star star-over fa fa-star "
                style="width:{{ product.get_star.1 }}%"></span>
    </div>
    <div class="star">
                <span class="star star-under fa fa-star"></span>
                <span class="star star-over fa fa-star "
                style="width:{{ product.get_star.2 }}%"></span>
    </div>
    <div class="star">
                <span class="star star-under fa fa-star"></span>
                <span class="star star-over fa fa-star "
                style="width:{{ product.get_star.3 }}%"></span>
    </div>
    <div class="star">
                <span class="star star-under fa fa-star"></span>
                <span class="star star-over fa fa-star "
                style="width:{{ product.get_star.4 }}%"></span>
    </div>
</div>

source/webapp/templates/product/update.html
{% extends 'base.html' %}
{% block title %}
    Изменить товар
{% endblock %}
{% block content %}
    <h1>Изменение Товара </h1>
     <form method="POST" enctype="multipart/form-data">
    {% include 'partial/form.html'%}
     <input type="submit" value="Изменить" class="btn text-center btn-primary">
    </form>
{% endblock %}